# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170218_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['posted']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
