# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170218_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
